### PR TITLE
Swift upgrade

### PR DESCRIPTION
**Pull request by FeXd**
Started working on upgrading to Swift 5+ so that development can continue. Actually started some months ago, and remembered I hadn't finished. Using the conversion tool required older versions of Xcode, which was a pain, but is done.

Currently the project is building but definitely has bugs and crashes happening. I just wanted to open this early so that folks knew it was being worked on.

### CODE REVIEW

**Comment by fspc** [comment]
Yay!

**Comment by FeXd** [comment]
It runs! Not working per se, but it's on a device and not crashing on tab change. 

Quick screen recording: [https://www.icloud.com/photos/#0eSUTTa_uzWp8HkvCM72XGJBQ](url)

@mrmomoko What should happen on first launch? I assume the "I'm New, I don't have a login" should likely be clickable?

**Comment by mrmomoko** [comment]
yeah, it should be clickable. 

It's a while since I went through the flow, I could maybe jump on a quick video call and walk you through if it's not obvious what to do. I could imagine it's not obvious for a lot of it.

**Comment by FeXd** [comment]
@mrmomoko I was able to get button working! A quick video call next week might be good if you have any free time next week. I can screen share what's done and see if you spot any obvious issues. Will email you!

**Comment by FeXd** [comment]
From what I can tell from my own testing, it appears that functionality has been restored. (I did not actively use the old version, so I'm a bit fuzzy on all functionality tho.)

There are still some visual / graphical issues that need to be fixed, but I'm thinking that it might be best for that work to be broken out into another pull request.

@mrmomoko or anyone else that is follow; could you build from my changes and see if you find any issues? If building is not an option, I can make a TestFlight build either from my own Apple account or invite me to the team.

**Pull request merged**
